// NOTE: This file is generated by uniwind and it should not be edited manually.
/// <reference types="uniwind/types" />

declare module "uniwind" {
  export interface UniwindConfig {
    themes: readonly [
      "light",
      "dark",
      "light_brand",
      "dark_brand",
      "light_info",
      "dark_info",
      "light_success",
      "dark_success",
      "light_warning",
      "dark_warning",
      "light_danger",
      "dark_danger",
    ];
  }
}

export {};
