// Color generation lives in src/theme-generator, shipped as
// `alouette/theme-generator` so an app generates its own palette the same way:
// this script only drives it for the default palette.

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { format } from "oxfmt";
import { generateTheme } from "../src/theme-generator/generateTheme.ts";

const srcDir = join(dirname(fileURLToPath(import.meta.url)), "../src");

const {
  css: defaultPaletteCss,
  oklchCss: defaultPaletteOklchCss,
  themeVariables,
} = generateTheme();

// Shared by the --animate-* tokens and the `animationDurationsMs` export, so
// Presence's `exitDurationMs` stays in step with the exit animation.
const animationDurationsMs = {
  slide: 600,
  collapse: 800,
  progress: 600,
  fade: 300,
  fast: 200,
} as const;

const animateTokens = {
  "slide-in": `slide-in ${animationDurationsMs.slide}ms cubic-bezier(0.16, 1, 0.3, 1)`,
  "slide-out": `slide-out ${animationDurationsMs.slide}ms cubic-bezier(0.16, 1, 0.3, 1)`,
  "collapse-in": `collapse-in ${animationDurationsMs.collapse}ms ease-out`,
  "collapse-out": `collapse-out ${animationDurationsMs.collapse}ms ease-out`,
} as const;

// What prefers-reduced-motion zeroes: one source for the web @media block and
// the map AlouetteProvider pushes on native, where react-native-css never
// matches that media feature. Durations are numbers because react-native-css
// compiles `200ms` to `200`.
const reducedMotionVariables = {
  "--default-transition-duration": 0,
  ...Object.fromEntries(
    Object.keys(animationDurationsMs).map((name) => [
      `--motion-duration-${name}`,
      0,
    ]),
  ),
  ...Object.fromEntries(
    Object.keys(animateTokens).map((name) => [`--animate-${name}`, "none"]),
  ),
};

const toCssValue = (value: string | number): string =>
  typeof value === "number" ? `${value}ms` : value;

// --- core.css ----------------------------------------------------------------
// Color-free: color utilities appear once a palette CSS is imported after it,
// since Tailwind v4 merges every @theme in the import graph. There is no
// @custom-variant for dark or the themes: ScopedTheme applies a theme (a class on
// web, the themeVariables map on native), never a `dark:` utility variant.
const coreCss = `/* Generated by scripts/build-css.ts. DO NOT EDIT. */
@import "tailwindcss/theme.css" layer(theme);
@import "tailwindcss/preflight.css" layer(base);
@import "tailwindcss/utilities.css";
@import "nativewind/theme";

@theme {
  /* The paired --text-*--line-height is what gives the text-* utility a default
     line-height (Tailwind v4 convention). Ratios are unitless: web treats them as
     font-size-relative and NativeWind multiplies a unitless lineHeight by
     fontSize, so both platforms agree. The display sizes (2xl and up) are
     heading-only and take tighter ratios; a heading at a shared size
     (text-lg/text-xl) tightens with an explicit leading-* class. */
  --text-xs: 0.75rem;    /* 12px */
  --text-xs--line-height: 1.4;
  --text-sm: 0.875rem;   /* 14px */
  --text-sm--line-height: 1.4;
  --text-base: 1rem;     /* 16px */
  --text-base--line-height: 1.4;
  --text-lg: 1.125rem;   /* 18px */
  --text-lg--line-height: 1.4;
  --text-xl: 1.5rem;     /* 24px */
  --text-xl--line-height: 1.4;
  --text-2xl: 2rem;      /* 32px */
  --text-2xl--line-height: 1.2;
  --text-3xl: 2.5rem;    /* 40px */
  --text-3xl--line-height: 1.1;
  --text-4xl: 3rem;      /* 48px */
  --text-4xl--line-height: 1.1;
  --text-5xl: 4rem;      /* 64px */
  --text-5xl--line-height: 1.1;
  --text-6xl: 5rem;      /* 80px */
  --text-6xl--line-height: 1.1;

  /* radius */
  --radius-xs: 0.5rem;
  --radius-sm: 1rem;
  --radius-md: 2rem;
  --radius-lg: 3rem;

  /* box-shadows — the layer colors are palette tokens, so each mode tunes them: Tailwind
     inlines this value into the utility (only its colors stay var()s), so a theme
     block redeclaring --shadow-* would change nothing. Each var() has a fixed
     fallback so a palette generated without the shadow tokens still yields a
     valid box-shadow. */
  --shadow-s: inset 0 1px 2px var(--color-shadow-highlight, #ffffff40), 0 1px 2px var(--color-dark-shadow, #00000040), 0 2px 4px var(--color-soft-shadow, #00000025);
  --shadow-m: inset 0 1px 2px var(--color-shadow-highlight, #ffffff40), 0 2px 4px var(--color-dark-shadow, #00000040), 0 4px 8px var(--color-soft-shadow, #00000025);
  --shadow-l: inset 0 1px 2px var(--color-shadow-highlight, #ffffff40), 0 4px 6px var(--color-dark-shadow, #00000040), 0 6px 10px var(--color-soft-shadow, #00000025);
  --shadow-lowered: inset 0 1px 2px var(--color-shadow-lowered-dark, #00000040), inset 0 -2px 2px var(--color-shadow-lowered-highlight, #ffffff15);
  /* downward-only and no inset highlight: a screen-spanning bar (app header)
     casts a shadow on the page below it, it is not a raised control. */
  --shadow-bar: 0 1px 2px var(--color-bar-dark-shadow, #00000020), 0 6px 16px var(--color-bar-soft-shadow, #00000018);

  /* spacing */
  --spacing-xxs: 4px;
  --spacing-xs: 8px;
  --spacing-sm: 12px;
  --spacing-m: 16px;
  --spacing-md: 16px;
  --spacing-l: 24px;
  --spacing-lg: 24px;
  --spacing-xl: 32px;
  --spacing-xxl: 48px;
  --spacing-3xl: 64px;
  --spacing-4xl: 128px;

  /* breakpoints — must match Breakpoints.ts */
  --breakpoint-sm: 480px;
  --breakpoint-md: 768px;
  --breakpoint-lg: 1024px;
  --breakpoint-xl: 1280px;

  /* animations — NativeWind runs the @keyframes on native via Reanimated. A CSS animation
     cannot play on unmount: pair an exit animation with <Presence>, which keeps
     the outgoing child mounted. */
${Object.entries(animateTokens)
  .map(([name, value]) => `  --animate-${name}: ${value};`)
  .join("\n")}
}

@layer theme {
  /* font-family tokens — overridable from an app's own @layer theme :root.
     The web values are a fallback list because the two web targets load different families:
       - Expo web: expo-font registers weight-specific families
         ('SoraRegular'/'SoraBold'/'SoraExtraBold', 'ChivoMono*'), no 'Sora'.
       - Vite Storybook: Google Fonts loads the single 'Sora'/'Chivo Mono'
         families, weight via font-weight.
     Native takes single names (React Native has no fallback list) under
     @variant native, which web drops. */
  :root {
    --font-body: "SoraRegular", "Sora", ui-sans-serif, system-ui, sans-serif;
    --font-body-bold: "SoraBold", "Sora", ui-sans-serif, system-ui, sans-serif;
    --font-body-extrabold: "SoraExtraBold", "Sora", ui-sans-serif, system-ui, sans-serif;
    --font-heading: "SoraRegular", "Sora", ui-sans-serif, system-ui, sans-serif;
    --font-heading-bold: "SoraBold", "Sora", ui-sans-serif, system-ui, sans-serif;
    --font-heading-extrabold: "SoraExtraBold", "Sora", ui-sans-serif, system-ui, sans-serif;
    --font-mono: "ChivoMonoRegular", "ChivoMono", "Chivo Mono", ui-monospace, SFMono-Regular, Menlo, monospace;
    --font-mono-bold: "ChivoMonoBold", "ChivoMono", "Chivo Mono", ui-monospace, SFMono-Regular, Menlo, monospace;
    --font-mono-extrabold: "ChivoMonoExtraBold", "ChivoMono", "Chivo Mono", ui-monospace, SFMono-Regular, Menlo, monospace;

    @variant native {
      --font-body: "SoraRegular";
      --font-body-bold: "SoraBold";
      --font-body-extrabold: "SoraExtraBold";
      --font-heading: "SoraRegular";
      --font-heading-bold: "SoraBold";
      --font-heading-extrabold: "SoraExtraBold";
      --font-mono: "ChivoMonoRegular";
      --font-mono-bold: "ChivoMonoBold";
      --font-mono-extrabold: "ChivoMonoExtraBold";
    }

    /* named transition durations, read by the duration-* utilities — variables
       so that reduced motion can zero them (see the @media block below) */
${Object.entries(animationDurationsMs)
  .map(([name, ms]) => `    --motion-duration-${name}: ${ms}ms;`)
  .join("\n")}
  }
}

/* prefers-reduced-motion: every alouette transition and animation token
   collapses to nothing. Unlayered so it wins over an app's @layer theme
   overrides. Native never matches this query: AlouetteProvider pushes the
   same values (reducedMotionVariables.ts) from AccessibilityInfo instead. */
@media (prefers-reduced-motion: reduce) {
  :root {
${Object.entries(reducedMotionVariables)
  .map(([name, value]) => `    ${name}: ${toCssValue(value)};`)
  .join("\n")}
  }
}

@layer base {
  /* hotpink flags any text rendered outside a <Text> */
  body { color: hotpink; }

  /* reset - equivalent to ScrollViewStyleReset */
  #root,#storybook-root,body,html{height:100%;display:flex;flex-direction: column;}
  body{overflow:hidden}

  /* let height/width keyframes interpolate to/from auto (collapse-in/out) on web */
  :root { interpolate-size: allow-keywords; }

  /* scrollbar-width/-color have no native equivalent, so this sits behind the
     @supports guard the native compiler cannot evaluate and therefore drops.
     Global rather than a utility: ScrollView maps className to the style prop,
     so a raw CSS class would not reach the DOM node that scrolls.
     The track is opaque: a scroll container's background paints across its whole
     padding box, gutter included, while its content container stops at the
     gutter's inner edge — so a transparent track bares the scroller's own ground
     (half of each color of a two-tone gradient frame such as AppShell's).
     \`lowered\` is the inset ground a track should have. The *
     selector re-declares the property on every element, so a nested scroller
     resolves its own theme's \`lowered\` rather than inheriting an ancestor's
     track. */
  @supports (display: contents) {
    * {
      scrollbar-width: thin;
      scrollbar-color: var(--color-border-sharp) var(--color-lowered);
    }
  }
}

/* keyframes */
@keyframes slide-in {
  from {
    opacity: 0;
    transform: translateX(-100%) rotateY(-90deg);
  }
  to {
    opacity: 1;
    transform: translateX(0) rotateY(0deg);
  }
}

@keyframes slide-out {
  from {
    opacity: 1;
    transform: translateX(0);
  }
  to {
    opacity: 0;
    transform: translateX(100%);
  }
}

@keyframes collapse-in {
  from {
    opacity: 0;
    height: 0;
  }
  to {
    opacity: 1;
    height: auto;
  }
}

@keyframes collapse-out {
  from {
    opacity: 1;
    height: auto;
  }
  to {
    opacity: 0;
    height: 0;
  }
}


/* named transition durations */
${Object.keys(animationDurationsMs)
  .map(
    (name) =>
      `@utility duration-${name} { transition-duration: var(--motion-duration-${name}); }`,
  )
  .join("\n")}

/* font-family + weight utilities.
   font-synthesis: none — on Expo web the weight-specific family ('SoraBold') is a
   single registered face, so the font-weight must not faux-bold already-bold
   glyphs. On Vite 'Sora' is a variable font, where the font-weight selects the
   real weight. */
@utility font-body            { font-family: var(--font-body);            font-weight: 400; font-synthesis: none; }
@utility font-body-bold       { font-family: var(--font-body-bold);       font-weight: 700; font-synthesis: none; }
@utility font-body-extrabold  { font-family: var(--font-body-extrabold);  font-weight: 800; font-synthesis: none; }
@utility font-heading           { font-family: var(--font-heading);           font-weight: 400; font-synthesis: none; }
@utility font-heading-bold      { font-family: var(--font-heading-bold);      font-weight: 700; font-synthesis: none; }
@utility font-heading-extrabold { font-family: var(--font-heading-extrabold); font-weight: 800; font-synthesis: none; }
@utility font-mono            { font-family: var(--font-mono);            font-weight: 400; font-synthesis: none; }
@utility font-mono-bold       { font-family: var(--font-mono-bold);       font-weight: 700; font-synthesis: none; }
@utility font-mono-extrabold  { font-family: var(--font-mono-extrabold);  font-weight: 800; font-synthesis: none; }

/* tripwire — a standalone font-weight has no effect on native, where each weight
   is its own font file (font-body-bold, …). These render visibly thin and cramped
   on web so an accidental use is easy to spot. */
@utility font-thin       { font-weight: 100; letter-spacing: -0.1em; }
@utility font-extralight { font-weight: 100; letter-spacing: -0.1em; }
@utility font-light      { font-weight: 100; letter-spacing: -0.1em; }
@utility font-normal     { font-weight: 100; letter-spacing: -0.1em; }
@utility font-medium     { font-weight: 100; letter-spacing: -0.1em; }
@utility font-semibold   { font-weight: 100; letter-spacing: -0.1em; }
@utility font-bold       { font-weight: 100; letter-spacing: -0.1em; }
@utility font-extrabold  { font-weight: 100; letter-spacing: -0.1em; }
@utility font-black      { font-weight: 100; letter-spacing: -0.1em; }

/* text-base-size-only — the body size without the line-height text-base
   pairs with it. A single-line native TextInput must not carry a line-height:
   iOS pins the field's line box to min == max == that height and leaves the
   extra leading above the glyphs, so the value renders below the middle of the
   box while the placeholder — drawn without those attributes — stays centered.
   Web needs no such thing (an <input> centers its text whatever the
   line-height is), so pair it as \`web:text-base native:text-base-size-only\`. */
@utility text-base-size-only {
  font-size: var(--text-base);
}

/* lowered — one class so the recessed ground and its inset shadow cannot
   drift apart */
@utility lowered {
  @apply bg-lowered shadow-lowered;
}

/* surface — the raised card. overflow-hidden clips children to the rounded
   corners. Any class written after it wins: it sorts ahead of bg-*, shadow-*,
   p-*, rounded-*, lowered and the surface-{size} utilities. The transition
   fades the ground when the accent or the mode swaps the theme variables
   under it. */
@utility surface {
  @apply overflow-hidden bg-surface shadow-s surface-md transition-colors duration-fast;
}

/* surface-{size} — padding and radius as one class so the pair cannot drift
   apart between call sites. A single p-* / rounded-* written after it still
   overrides one side. */
@utility surface-xxs {
  @apply p-xs rounded-xs;
}
@utility surface-xs {
  @apply p-sm rounded-xs;
}
@utility surface-sm {
  @apply p-m rounded-sm;
}
@utility surface-md {
  @apply p-xl rounded-sm;
}
@utility surface-lg {
  @apply p-xxl rounded-md;
}

/* surface-popover — the panel of Menu, Select and InputTextAutocomplete. Its
   rows are rounded-xs, so p-xs + rounded-sm keeps their corners concentric
   with the panel's. */
@utility surface-popover {
  @apply overflow-hidden bg-highlight shadow-l rounded-sm p-xs;
}

/* flex-center — not \`center\`, which would clash with a text-align /
   place-* shorthand */
@utility flex-center {
  align-items: center;
  justify-content: center;
}

/* flex-wrap-balance — \`balance\` evens out the item count across lines, so
   the last row is never a lone orphan. Only Safari 26+ implements it;
   elsewhere (and on native, where the compiler drops the feature query) it
   stays plain \`wrap\`. */
@utility flex-wrap-balance {
  flex-wrap: wrap;
  @supports (flex-wrap: balance) {
    flex-wrap: balance;
  }
}

/* An all-caps label (Avatar initials) centered on its line box sits ~1px high:
   the box spans ascender + descender, and caps have no descender. Trimming it to
   cap height over baseline centers the ink. Web only: native (where the compiler
   drops the feature query) and browsers without \`text-box\` keep the line box. */
@utility text-trim-cap {
  @supports (text-box: trim-both cap alphabetic) {
    text-box: trim-both cap alphabetic;
  }
}
`;

writeFileSync(join(srcDir, "core.css"), coreCss);
console.log(`Wrote ${join(srcDir, "core.css")}`);

// --- default-palette.css -----------------------------------------------------
const defaultPaletteFile = `/* Generated by scripts/build-css.ts. DO NOT EDIT.
   Default alouette palette in sRGB hex (optional). Import after
   'alouette/core.css'. Complete on its own — add
   'alouette/default-palette-oklch.css' after it to opt web into the wide-gamut
   ramp. A BYO app imports its own generateTheme() palette CSS instead. */
${defaultPaletteCss}`;

writeFileSync(join(srcDir, "default-palette.css"), defaultPaletteFile);
console.log(`Wrote ${join(srcDir, "default-palette.css")}`);

// --- default-palette-oklch.css -----------------------------------------------
const defaultPaletteOklchFile = `/* Generated by scripts/build-css.ts. DO NOT EDIT.
   Wide-gamut half of the default alouette palette (optional). Import after
   'alouette/default-palette.css' to opt web into the display-p3 ramp; omit it to
   stay on sRGB hex everywhere. */
${defaultPaletteOklchCss}`;

writeFileSync(
  join(srcDir, "default-palette-oklch.css"),
  defaultPaletteOklchFile,
);
console.log(`Wrote ${join(srcDir, "default-palette-oklch.css")}`);

// --- global.css --------------------------------------------------------------
const globalCss = `/* Generated by scripts/build-css.ts. DO NOT EDIT.
   Aggregator: alouette's structural core + the default sRGB palette. Add
   \`@import "alouette/default-palette-oklch.css";\` after this to opt web into
   the wide-gamut ramp. BYO-palette apps import "alouette/core.css" + their own
   generated palette CSS instead. */
@import "./core.css";
@import "./default-palette.css";
`;

writeFileSync(join(srcDir, "global.css"), globalCss);
console.log(`Wrote ${join(srcDir, "global.css")}`);

// --- themeVariables.ts -------------------------------------------------------
// Native never reads the .<theme> CSS blocks, so ScopedTheme feeds NativeWind's
// VariableContextProvider from this map instead. Each theme is resolved (base
// mode tokens + accent overrides merged) so it can be applied at any depth and
// still carry every --color-* token. There is no oklch map: web resolves every
// token from CSS, and native parses hex only.
interface WriteThemeVariablesModuleParams {
  fileName: string;
  variables: Record<string, Record<string, string>>;
  doc: string;
}

const writeThemeVariablesModule = async ({
  fileName,
  variables,
  doc,
}: WriteThemeVariablesModuleParams): Promise<void> => {
  const path = join(srcDir, fileName);
  const { code } = await format(
    path,
    `/* Generated by scripts/build-css.ts. DO NOT EDIT. */\n/* eslint-disable camelcase */
import { Platform } from "react-native";
import type { AlouetteTheme } from "./core/AlouetteConfig";

/**
 * ${doc}
 */
export const themeVariables: Record<
  AlouetteTheme,
  Record<\`--\${string}\`, string>
> = Platform.OS === "web" ? {} as any : ${JSON.stringify(variables, null, 2)};
`,
    { printWidth: 80 },
  );

  writeFileSync(path, code);
  console.log(`Wrote ${path}`);
};

await writeThemeVariablesModule({
  fileName: "defaultThemeVariablesSrgb.ts",
  variables: themeVariables,
  doc: `Resolved CSS-variable maps for every theme in sRGB hex, shared with
 * default-palette.css. Feeds \`ScopedTheme\` (NativeWind's
 * \`VariableContextProvider\`) on every platform but web.`,
});

// --- animationDurationsMs.ts -------------------------------------------------
const animationDurationsTs = `/* Generated by scripts/build-css.ts. DO NOT EDIT. */

/**
 * Duration (in ms) of each generic motion, mirroring the \`--animate-*\` CSS
 * tokens. Pass the matching value as \`exitDurationMs\` to {@link PresenceOne} /
 * {@link PresenceList} so the exit timer matches the CSS animation.
 */
export const animationDurationsMs = ${JSON.stringify(animationDurationsMs, null, 2)} as const;
`;

writeFileSync(join(srcDir, "animationDurationsMs.ts"), animationDurationsTs);
console.log(`Wrote ${join(srcDir, "animationDurationsMs.ts")}`);

// --- reducedMotionVariables.ts -----------------------------------------------
const reducedMotionVariablesTs = `/* Generated by scripts/build-css.ts. DO NOT EDIT. */

/**
 * The motion tokens zeroed under reduced motion, shared with core.css's
 * \`@media (prefers-reduced-motion: reduce)\` block. Native cannot evaluate that
 * query, so \`AlouetteProvider\` pushes this map through NativeWind's
 * \`VariableContextProvider\` when the OS setting is on.
 */
export const reducedMotionVariables = ${JSON.stringify(reducedMotionVariables, null, 2)} as const;
`;

writeFileSync(
  join(srcDir, "reducedMotionVariables.ts"),
  reducedMotionVariablesTs,
);
console.log(`Wrote ${join(srcDir, "reducedMotionVariables.ts")}`);
