// Generates the alouette CSS + JS token mirrors. Run via
// `pnpm --filter alouette build:css`.
//
// Color generation lives in src/theme-generator (shipped and exported as
// `alouette/theme-generator` so apps can produce their own palette). This driver
// only assembles the *default* outputs:
//   - src/core.css            structural only (type/radius/shadow/spacing/anim,
//                             fonts, base, keyframes, utilities) — NO --color-*.
//   - src/default-palette.css the default palette in sRGB hex (@theme color
//                             defaults + the twelve .<theme> blocks, the latter
//                             behind a web-only feature query) =
//                             generateTheme().css.
//   - src/default-palette-oklch.css  optional wide-gamut overlay re-declaring the
//                             same tokens as oklch() behind @supports =
//                             generateTheme().oklchCss. Import after the palette
//                             to opt web into display-p3 chroma.
//   - src/global.css          convenience aggregator importing core + the sRGB
//                             palette, so existing
//                             `@import "alouette/global.css"` consumers still work.
//   - src/defaultThemeVariablesSrgb.ts   runtime default map, sRGB hex.
//   - src/animationDurationsMs.ts  JS mirror of the --animate-* durations.
//
// A BYO-palette app imports `alouette/core.css` + its own generated palette CSS
// (never default-palette.css) and passes its generated themeVariables to
// <AlouetteProvider themeVariables={...}>.

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { format } from "oxfmt";
import { generateTheme } from "../src/theme-generator/generateTheme.ts";

const srcDir = join(dirname(fileURLToPath(import.meta.url)), "../src");

const {
  css: defaultPaletteCss,
  oklchCss: defaultPaletteOklchCss,
  themeVariables,
} = generateTheme();

// Duration (ms) of each generic motion. The single source of truth for both the
// CSS @keyframes/--animate-* tokens and the JS `animationDurationsMs` export
// (Presence's `exitDurationMs` must match the exit animation here). Exposed from
// the framework so consumers reference it instead of hardcoding the number — if
// a duration changes, only this value moves.
const animationDurationsMs = {
  slide: 600,
  collapse: 800,
  progress: 600,
  fade: 300,
  fast: 200,
} as const;

// --- core.css ----------------------------------------------------------------
// Structural, color-free. Color utilities generate once a palette CSS (this
// default or an app's own) is imported after core.css — Tailwind v4 merges every
// @theme in the import graph. NB: no @custom-variant for dark/themes. Theming is
// applied via ScopedTheme (NativeWind's VariableContextProvider) using the
// generated themeVariables map, not via `dark:`/theme utility variants.
const coreCss = `/* Generated by scripts/build-css.ts. DO NOT EDIT. */
@import "tailwindcss/theme.css" layer(theme);
@import "tailwindcss/preflight.css" layer(base);
@import "tailwindcss/utilities.css";
@import "nativewind/theme";

@theme {
  /* unified alouette type scale — standard Tailwind names, exact pixel values preserved.
     The paired --text-*--line-height modifier is what makes the text-* utility carry a
     default line-height (Tailwind v4 convention). Without it, line-height stays unset.
     Ratios are unitless: web treats them as font-size-relative; on native NativeWind
     multiplies any unitless lineHeight by fontSize, so they behave identically on both platforms.
     Body default is 1.4 (matches the old Tamagui body font); the heading-only display
     sizes (32/40/64px) use the old heading ratios. For headings at shared sizes
     (text-lg/text-xl), add an explicit leading-* class to tighten. */
  --text-xs: 0.75rem;    /* 12px */
  --text-xs--line-height: 1.4;
  --text-sm: 0.875rem;   /* 14px */
  --text-sm--line-height: 1.4;
  --text-base: 1rem;     /* 16px */
  --text-base--line-height: 1.4;
  --text-lg: 1.125rem;   /* 18px */
  --text-lg--line-height: 1.4;
  --text-xl: 1.5rem;     /* 24px */
  --text-xl--line-height: 1.4;
  --text-2xl: 2rem;      /* 32px */
  --text-2xl--line-height: 1.2;
  --text-3xl: 2.5rem;    /* 40px */
  --text-3xl--line-height: 1.1;
  --text-4xl: 3rem;      /* 48px */
  --text-4xl--line-height: 1.1;
  --text-5xl: 4rem;      /* 64px */
  --text-5xl--line-height: 1.1;
  --text-6xl: 5rem;      /* 80px */
  --text-6xl--line-height: 1.1;

  /* radius — alouette scale (16px base) */
  --radius-xs: 0.5rem;
  --radius-sm: 1rem;
  --radius-md: 2rem;
  --radius-lg: 3rem;

  /* box-shadows — multi-layer with inset highlight, matches original
     containers/variants.ts. Names map to Tailwind's shadow-{name} utilities. */
  --shadow-s: inset 0 1px 2px #ffffff40, 0 1px 2px #00000040, 0 2px 4px #00000025;
  --shadow-m: inset 0 1px 2px #ffffff40, 0 2px 4px #00000040, 0 4px 8px #00000025;
  --shadow-l: inset 0 1px 2px #ffffff40, 0 4px 6px #00000040, 0 6px 10px #00000025;
  --shadow-lowered: inset 0 1px 2px #00000040, inset 0 -2px 2px #ffffff15;

  /* spacing — named scale matching the old $N.N token names */
  --spacing-xxs: 4px;
  --spacing-xs: 8px; /* previous $0.5 */
  --spacing-sm: 12px;
  --spacing-m: 16px; /* previous $1.0 */
  --spacing-md: 16px;
  --spacing-l: 24px;
  --spacing-lg: 24px;
  --spacing-xl: 32px; /* previous $2.0 */
  --spacing-xxl: 48px;
  --spacing-3xl: 64px; /* previous $3.0 */
  --spacing-4xl: 128px;

  /* breakpoints — match Breakpoints.ts */
  --breakpoint-sm: 480px;
  --breakpoint-md: 768px;
  --breakpoint-lg: 1024px;
  --breakpoint-xl: 1280px;

  /* animations — Tailwind v4 names the utility after the --animate-* key
     (animate-slide-in) and NativeWind runs the @keyframes on native via
     Reanimated. Names are generic motions, not component-specific. CSS
     animations are enter-only on their own; pair the exit animation with
     <Presence> (keeps the outgoing child mounted) for an AnimatePresence-style
     swap without an animation library. */
  --animate-slide-in: slide-in ${animationDurationsMs.slide}ms cubic-bezier(0.16, 1, 0.3, 1);
  --animate-slide-out: slide-out ${animationDurationsMs.slide}ms cubic-bezier(0.16, 1, 0.3, 1);
  --animate-collapse-in: collapse-in ${animationDurationsMs.collapse}ms ease-out;
  --animate-collapse-out: collapse-out ${animationDurationsMs.collapse}ms ease-out;
}

@layer theme {
  /* font-family tokens — consumers can override these in their own @layer theme :root to swap fonts.
     The base holds WEB values as a fallback list, because the two web targets load different
     families:
       - Expo web (react-native-web): expo-font registers weight-specific families
         ('SoraRegular'/'SoraBold'/'SoraExtraBold', 'ChivoMono*') — 'Sora' is NOT available.
       - Vite Storybook: Google Fonts loads the single 'Sora'/'Chivo Mono' families, weight via
         font-weight.
     Leading with the weight-specific name (matched on Expo web) and falling back to 'Sora'/'ChivoMono'
     (matched on Vite) makes both work from one declaration. Native uses single names (RN has no
     fallbacks) under @variant native (NativeWind's native: variant, from nativewind/theme).

     NB: the base holds the web values and the @variant native block overrides them on native only —
     the native: variant is dropped on web and applied by NativeWind's runtime on native, so the
     platform font split lives there. */
  :root {
    --font-body: "SoraRegular", "Sora", ui-sans-serif, system-ui, sans-serif;
    --font-body-bold: "SoraBold", "Sora", ui-sans-serif, system-ui, sans-serif;
    --font-body-extrabold: "SoraExtraBold", "Sora", ui-sans-serif, system-ui, sans-serif;
    --font-heading: "SoraRegular", "Sora", ui-sans-serif, system-ui, sans-serif;
    --font-heading-bold: "SoraBold", "Sora", ui-sans-serif, system-ui, sans-serif;
    --font-heading-extrabold: "SoraExtraBold", "Sora", ui-sans-serif, system-ui, sans-serif;
    --font-mono: "ChivoMonoRegular", "ChivoMono", "Chivo Mono", ui-monospace, SFMono-Regular, Menlo, monospace;
    --font-mono-bold: "ChivoMonoBold", "ChivoMono", "Chivo Mono", ui-monospace, SFMono-Regular, Menlo, monospace;
    --font-mono-extrabold: "ChivoMonoExtraBold", "ChivoMono", "Chivo Mono", ui-monospace, SFMono-Regular, Menlo, monospace;

    @variant native {
      --font-body: "SoraRegular";
      --font-body-bold: "SoraBold";
      --font-body-extrabold: "SoraExtraBold";
      --font-heading: "SoraRegular";
      --font-heading-bold: "SoraBold";
      --font-heading-extrabold: "SoraExtraBold";
      --font-mono: "ChivoMonoRegular";
      --font-mono-bold: "ChivoMonoBold";
      --font-mono-extrabold: "ChivoMonoExtraBold";
    }
  }
}

@layer base {
  /* hotpink default catches any text missing Text component use */
  body { color: hotpink; }

  /* let height/width keyframes interpolate to/from auto (collapse-in/out) on web */
  :root { interpolate-size: allow-keywords; }

  body, #root {
    display: flex;
    flex-direction: column;
    min-height: 100vh;
  }

  /* scrollbar-width/-color have no native equivalent, so this sits behind the
     @supports guard the native compiler cannot evaluate and therefore drops.
     Global rather than a utility: ScrollView maps className to the style prop,
     so a raw CSS class would not reach the DOM node that scrolls. */
  @supports (display: contents) {
    * {
      scrollbar-width: thin;
      scrollbar-color: var(--color-border-sharp) transparent;
    }
  }
}

/* keyframes referenced by the --animate-* theme tokens above. */
@keyframes slide-in {
  from {
    opacity: 0;
    transform: translateX(-100%) rotateY(-90deg);
  }
  to {
    opacity: 1;
    transform: translateX(0) rotateY(0deg);
  }
}

@keyframes slide-out {
  from {
    opacity: 1;
    transform: translateX(0);
  }
  to {
    opacity: 0;
    transform: translateX(100%);
  }
}

@keyframes collapse-in {
  from {
    opacity: 0;
    height: 0;
  }
  to {
    opacity: 1;
    height: auto;
  }
}

@keyframes collapse-out {
  from {
    opacity: 1;
    height: auto;
  }
  to {
    opacity: 0;
    height: 0;
  }
}


/* named transition durations — one per animationDurationsMs entry so transition
   classNames reference the same source of truth as the JS export (native drives
   the same motion via Reanimated withTiming(animationDurationsMs.*)). */
${Object.entries(animationDurationsMs)
  .map(
    ([name, ms]) =>
      `@utility duration-${name} { transition-duration: ${ms}ms; }`,
  )
  .join("\n")}

/* font-family + weight utilities — family×weight combinations; use with standard text-* size utilities.
   font-synthesis: none — on Expo web the weight-specific family ('SoraBold') is a single registered
   face, so the font-weight below must NOT trigger algorithmic (faux) bolding of already-bold glyphs.
   On Vite web 'Sora' is a real variable font, so the font-weight selects the genuine weight. */
@utility font-body            { font-family: var(--font-body);            font-weight: 400; font-synthesis: none; }
@utility font-body-bold       { font-family: var(--font-body-bold);       font-weight: 700; font-synthesis: none; }
@utility font-body-extrabold  { font-family: var(--font-body-extrabold);  font-weight: 800; font-synthesis: none; }
@utility font-heading           { font-family: var(--font-heading);           font-weight: 400; font-synthesis: none; }
@utility font-heading-bold      { font-family: var(--font-heading-bold);      font-weight: 700; font-synthesis: none; }
@utility font-heading-extrabold { font-family: var(--font-heading-extrabold); font-weight: 800; font-synthesis: none; }
@utility font-mono            { font-family: var(--font-mono);            font-weight: 400; font-synthesis: none; }
@utility font-mono-bold       { font-family: var(--font-mono-bold);       font-weight: 700; font-synthesis: none; }
@utility font-mono-extrabold  { font-family: var(--font-mono-extrabold);  font-weight: 800; font-synthesis: none; }

/* tripwire — standalone Tailwind font-weight utilities are NOT valid here: weight
   must be baked into the font-* family utility (font-body-bold, etc.) so it works on
   native. Override them to weight 100 + crunched letter-spacing so any accidental use
   renders visibly thin and cramped on web and is easy to spot. (native ignores both
   font-weight and letterSpacing here, so this only affects web.) */
@utility font-thin       { font-weight: 100; letter-spacing: -0.1em; }
@utility font-extralight { font-weight: 100; letter-spacing: -0.1em; }
@utility font-light      { font-weight: 100; letter-spacing: -0.1em; }
@utility font-normal     { font-weight: 100; letter-spacing: -0.1em; }
@utility font-medium     { font-weight: 100; letter-spacing: -0.1em; }
@utility font-semibold   { font-weight: 100; letter-spacing: -0.1em; }
@utility font-bold       { font-weight: 100; letter-spacing: -0.1em; }
@utility font-extrabold  { font-weight: 100; letter-spacing: -0.1em; }
@utility font-black      { font-weight: 100; letter-spacing: -0.1em; }

/* flex-center — center children on both axes. Replaces the old Box \`center\`
   variant. Named flex-center (not \`center\`) to avoid clashing with any future
   text-align / place-* shorthand. */
@utility flex-center {
  align-items: center;
  justify-content: center;
}
`;

writeFileSync(join(srcDir, "core.css"), coreCss);
console.log(`Wrote ${join(srcDir, "core.css")}`);

// --- default-palette.css -----------------------------------------------------
// The default palette in sRGB hex: the @theme color defaults (which generate
// bg-*, text-*, border-* utilities) plus the twelve .<theme> blocks.
// Optional — import after core.css. A BYO app imports its own
// generateTheme().css instead.
const defaultPaletteFile = `/* Generated by scripts/build-css.ts. DO NOT EDIT.
   Default alouette palette in sRGB hex (optional). Import after
   'alouette/core.css'. Complete on its own — add
   'alouette/default-palette-oklch.css' after it to opt web into the wide-gamut
   ramp. A BYO app imports its own generateTheme() palette CSS instead. */
${defaultPaletteCss}`;

writeFileSync(join(srcDir, "default-palette.css"), defaultPaletteFile);
console.log(`Wrote ${join(srcDir, "default-palette.css")}`);

// --- default-palette-oklch.css -----------------------------------------------
// The wide-gamut half, kept in its own file so oklch is opt-in: a project that
// wants the sRGB ramp everywhere never imports it. Purely additive — it
// re-declares the same tokens behind @supports, so it must come after the
// palette above.
const defaultPaletteOklchFile = `/* Generated by scripts/build-css.ts. DO NOT EDIT.
   Wide-gamut half of the default alouette palette (optional). Import after
   'alouette/default-palette.css' to opt web into the display-p3 ramp; omit it to
   stay on sRGB hex everywhere. */
${defaultPaletteOklchCss}`;

writeFileSync(
  join(srcDir, "default-palette-oklch.css"),
  defaultPaletteOklchFile,
);
console.log(`Wrote ${join(srcDir, "default-palette-oklch.css")}`);

// --- global.css --------------------------------------------------------------
// Convenience aggregator: structural core + the sRGB default palette. Keeps
// existing `@import "alouette/global.css"` consumers working. The oklch overlay
// is deliberately NOT included — it stays an explicit extra @import. BYO apps
// import core.css + their own palette CSS instead of this file.
const globalCss = `/* Generated by scripts/build-css.ts. DO NOT EDIT.
   Aggregator: alouette's structural core + the default sRGB palette. Add
   \`@import "alouette/default-palette-oklch.css";\` after this to opt web into
   the wide-gamut ramp. BYO-palette apps import "alouette/core.css" + their own
   generated palette CSS instead. */
@import "./core.css";
@import "./default-palette.css";
`;

writeFileSync(join(srcDir, "global.css"), globalCss);
console.log(`Wrote ${join(srcDir, "global.css")}`);

// --- themeVariables.ts -------------------------------------------------------
// NativeWind v5 styles every component through CSS variables, but it has no
// stable cross-platform API to read a variable in JS (useUnstableNativeVariable
// throws on web). We therefore emit the same theme data as a JS map, used both
// to feed VariableContextProvider (ScopedTheme) and to read tokens in JS
// (useThemeToken). It is the runtime default; a BYO app passes its own map to
// <AlouetteProvider themeVariables={...}>.
//
// Maps are *resolved* (base mode tokens + accent overrides merged) so a theme can
// be applied at any depth and still carry every --color-* token.
//
// Two variants, mirroring the two palette CSS files: sRGB hex (the default —
// `defaultThemeVariables.ts` re-exports it, and it is the only format React
// Native can parse) and oklch with display-p3 chroma headroom, which an app
// imports explicitly when it also imports default-palette-oklch.css.
interface WriteThemeVariablesModuleParams {
  fileName: string;
  variables: Record<string, Record<string, string>>;
  doc: string;
}

const writeThemeVariablesModule = async ({
  fileName,
  variables,
  doc,
}: WriteThemeVariablesModuleParams): Promise<void> => {
  const path = join(srcDir, fileName);
  const { code } = await format(
    path,
    `/* Generated by scripts/build-css.ts. DO NOT EDIT. */\n/* eslint-disable camelcase */
import { Platform } from "react-native";
import type { AlouetteTheme } from "./core/AlouetteConfig";

/**
 * ${doc}
 */
export const themeVariables: Record<
  AlouetteTheme,
  Record<\`--\${string}\`, string>
> = Platform.OS === "web" ? {} as any : ${JSON.stringify(variables, null, 2)};
`,
    { printWidth: 80 },
  );

  writeFileSync(path, code);
  console.log(`Wrote ${path}`);
};

await writeThemeVariablesModule({
  fileName: "defaultThemeVariablesSrgb.ts",
  variables: themeVariables,
  doc: `Resolved CSS-variable maps for every theme in sRGB hex, shared with
 * default-palette.css. Feeds \`ScopedTheme\` (NativeWind's
 * \`VariableContextProvider\`) and \`useThemeToken\` on every platform but web.`,
});

// No oklch counterpart: web resolves every token from default-palette-oklch.css,
// so the map only ever needs the hex values native parses.

// --- animationDurationsMs.ts -------------------------------------------------
// JS mirror of the --animate-* token durations above, so consumers (e.g.
// Presence's `exitDurationMs`) reference the framework value instead of
// hardcoding it. Same single-source-of-truth pattern as themeVariables.ts.
const animationDurationsTs = `/* Generated by scripts/build-css.ts. DO NOT EDIT. */

/**
 * Duration (in ms) of each generic motion, mirroring the \`--animate-*\` CSS
 * tokens. Pass the matching value as \`exitDurationMs\` to {@link PresenceOne} /
 * {@link PresenceList} so the exit timer matches the CSS animation.
 */
export const animationDurationsMs = ${JSON.stringify(animationDurationsMs, null, 2)} as const;
`;

writeFileSync(join(srcDir, "animationDurationsMs.ts"), animationDurationsTs);
console.log(`Wrote ${join(srcDir, "animationDurationsMs.ts")}`);
