allowBuilds:
  esbuild: true
  unrs-resolver: true
dedupePeerDependents: true
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@pob/*"
  - pob-dependencies
  - check-package-dependencies
  - alouette
  - alouette-icons
  - nightingale
  - nightingale-logger
  - "@expo/cli"
  - "@expo/fingerprint"
  - "@expo/inline-modules"
  - "@expo/local-build-cache-provider"
  - "@expo/metro-config"
  - "@expo/prebuild-config"
  - expo-asset
  - expo-constants
  - expo-server
  - expo
nodeLinker: hoisted
packages:
  - packages/*
savePrefix: ^
